name: Notify Microsoft Teams on PR

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
    - name: Notify Teams
      uses: Skitionek/notify-microsoft-teams@v1.0.8
      with:
        webhook_url: ${{ secrets.TEAMS_WEBHOOK_URI }}
        raw: '{"title": "Ваш заголовок", "text": "Ваше сообщение"}'